@host = http://localhost:7094

### Get all games

GET {{host}}/api/games
Accept: application/json

### Create game

POST {{host}}/api/games
Content-Type: application/json

{
  "title": "Resident Evil 2",
  "description": "A survival-horror game.",
  "releaseDate": "1998-01-21"
}
