<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\GamePond.Application\GamePond.Application.csproj" />
      <ProjectReference Include="..\GamePond.Domain\GamePond.Domain.csproj" />
    </ItemGroup>

</Project>
